#!/bin/bash

# File to store the last used directory
config_file="$HOME/.github_download_config"

# Load the last used directory from the config file
if [ -f "$config_file" ]; then
    last_used_directory=$(cat "$config_file")
else
    last_used_directory="$HOME"
fi

# Prompt user for GitHub repository URL
repo_url=$(zenity --entry --title="GitHub Repository URL" --text="Enter GitHub repository URL:" --width=400)

# Check if the user clicked Cancel or closed the dialog
if [ $? -ne 0 ]; then
    exit 1
fi

# Prompt user for the folder path within the repository
folder_path=$(zenity --entry --title="Folder Path" --text="Enter folder path within the repository:" --width=400)

# Check if the user clicked Cancel or closed the dialog
if [ $? -ne 0 ]; then
    exit 1
fi

# Prompt user for destination folder on the local machine
destination_folder=$(zenity --file-selection --directory --title="Select Destination Folder" --filename="$last_used_directory")

# Check if the user clicked Cancel or closed the dialog
if [ $? -ne 0 ]; then
    exit 1
fi

# Save the chosen directory to the config file
echo "$destination_folder" > "$config_file"

# Download the ZIP archive of the specified folder
curl -LkSs "$repo_url/archive/refs/heads/main.zip" -o "$destination_folder.zip"

# Unzip the archive and remove unnecessary files
unzip -qq "$destination_folder.zip" "$repo_url-main/$folder_path/*" -d "$destination_folder"
rm "$destination_folder.zip"

# Provide success message
zenity --info --title="Success" --text="Folder downloaded successfully to: $destination_folder"
