#!/bin/bash

# Function to clone GitLab repositories
clone_gitlab_repositories() {
    access_token="$1"
    repositories=("your_gitlab_repo1" "your_gitlab_repo2" "your_gitlab_repo3")

    for repo in "${repositories[@]}"; do
        git clone --quiet "https://$access_token@gitlab.com/your_username/$repo.git"
    done
}

# Get GitLab credentials
gitlab_username=$(whiptail --inputbox "Enter your GitLab username:" 10 60 --title "GitLab Login" 3>&1 1>&2 2>&3)
gitlab_token=$(whiptail --passwordbox "Enter your GitLab personal access token:" 10 60 --title "GitLab Login" 3>&1 1>&2 2>&3)

# Clone GitLab repositories
clone_gitlab_repositories "$gitlab_token"

# Display success message
whiptail --msgbox "GitLab repositories cloned successfully." 10 60 --title "Success"
